version: '3.8'

services:
  rust-iptv-proxy:
    image: lisankai93/rust-iptv-proxy:latest
    container_name: rust-iptv-proxy
    ports:
      - "7878:7878"
    command: [
      "--user", "02041300434",
      "--passwd", "31253530",
      "--mac", "50:01:6b:33:46:be",
      "--bind", "0.0.0.0:7878",
      "--rtsp-proxy"
    ]
    environment:
      - RUST_LOG=debug
    restart: unless-stopped
    volumes:
      # 映射数据目录到容器的/data
      - ./data:/data
      - ./logs:/logs
      # 移除 static 映射，使用 Docker 镜像中内置的静态文件
    working_dir: /data
    # 如果需要 UDP 多播或特定网络接口，请启用 host 网络模式
    # network_mode: host
