version: '3.8'

services:
  iptv-proxy:
    image: your-dockerhub-username/rust-iptv-proxy:latest
    ports:
      - "7878:7878"
    command: [
      "--user", "${IPTV_USER}",
      "--passwd", "${IPTV_PASSWD}",
      "--mac", "${IPTV_MAC}",
      "--bind", "0.0.0.0:7878",
      "--rtsp-proxy"
      # 可选参数，根据需要取消注释：
      # "--udp-proxy",
      # "--imei", "${IPTV_IMEI}",
      # "--address", "${IPTV_ADDRESS}",
      # "--interface", "${IPTV_INTERFACE}",
      # "--extra-playlist", "${IPTV_EXTRA_PLAYLIST}",
      # "--extra-xmltv", "${IPTV_EXTRA_XMLTV}",
      # "--channel-mapping", "CCTV -1综合高清=CCTV-1综合,CCTV -2财经高清=CCTV-2财经,CCTV -7军事农业高清=CCTV-7国防军事,CCTV-10科教高清=CCTV-10科教,CCTV-5超清=CCTV-5体育,CCTV-1高清4M=CCTV-1综合,CCTV1-1M开机标清=CCTV-1综合"
    ]
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    # 如果需要 UDP 多播或特定网络接口，请启用 host 网络模式
    # network_mode: host