version: '3.8'

services:
  iptv-proxy:
    build: .
    ports:
      - "7878:7878"
    command: [
      "--user", "your_username",
      "--passwd", "your_password", 
      "--mac", "your_mac_address",
      "--bind", "0.0.0.0:7878",
      "--rtsp-proxy",
      "--channel-mapping", "CCTV -1综合高清=CCTV-1综合,CCTV -2财经高清=CCTV-2财经,CCTV -7军事农业高清=CCTV-7国防军事,CCTV-10科教高清=CCTV-10科教,CCTV-5超清=CCTV-5体育,CCTV-1高清4M=CCTV-1综合,CCTV1-1M开机标清=CCTV-1综合"
    ]
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    # 如果需要 UDP 多播或特定网络接口，请启用 host 网络模式
    # network_mode: host